### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by yvecai** [geofabrik/meta2tile#2]
Was using metat2tile for a while, but I have now a segfault on a new server (Debian Stretch).
```

$ ./meta2tile --verbose --bbox -5,42,8,51.5 --mbtiles /home/admin/Planet/tools/meta2tile_links/ /var/tmp/france_pistes_only.mbt

Converting tiles from directory /home/admin/Planet/tools/meta2tile_links/ to mbtiles file /var/tmp/france_pistes_only.mbt

opened '/var/tmp/france_pistes_only.mbt' for mbtiles output

Segmentation fault
```

Here is Valgrind output

> opened '/var/tmp/france_pistes_only.mbt' for mbtiles output
==32139== Conditional jump or move depends on uninitialised value(s)
==32139==    at 0x4C31CAE: __memcmp_sse4_1 (vg_replace_strmem.c:1094)
==32139==    by 0x10A99A: ispng (meta2tile.c:159)
==32139==    by 0x10BAEA: expand_meta (meta2tile.c:522)
==32139==    by 0x10CC47: descend (meta2tile.c:830)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10D9D5: main (meta2tile.c:1174)
==32139== 
==32139== Use of uninitialised value of size 8
==32139==    at 0x4C31CF5: __memcmp_sse4_1 (vg_replace_strmem.c:1094)
==32139==    by 0x10A99A: ispng (meta2tile.c:159)
==32139==    by 0x10BAEA: expand_meta (meta2tile.c:522)
==32139==    by 0x10CC47: descend (meta2tile.c:830)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10D9D5: main (meta2tile.c:1174)
==32139== 
==32139== 
==32139== Process terminating with default action of signal 11 (SIGSEGV)
==32139==  Bad permissions for mapped region at address 0x824B384
==32139==    at 0x4C31CF5: __memcmp_sse4_1 (vg_replace_strmem.c:1094)
==32139==    by 0x10A99A: ispng (meta2tile.c:159)
==32139==    by 0x10BAEA: expand_meta (meta2tile.c:522)
==32139==    by 0x10CC47: descend (meta2tile.c:830)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10CC00: descend (meta2tile.c:824)
==32139==    by 0x10D9D5: main (meta2tile.c:1174)
==32139== 
==32139== HEAP SUMMARY:
==32139==     in use at exit: 1,048,890 bytes in 4,017 blocks
==32139==   total heap usage: 5,472 allocs, 1,455 frees, 1,479,546 bytes allocated
==32139== 
==32139== LEAK SUMMARY:
==32139==    definitely lost: 64 bytes in 1 blocks
==32139==    indirectly lost: 0 bytes in 0 blocks
==32139==      possibly lost: 4,104 bytes in 1 blocks
==32139==    still reachable: 1,044,722 bytes in 4,015 blocks
==32139==                       of which reachable via heuristic:
==32139==                         length64           : 463,488 bytes in 186 blocks
==32139==         suppressed: 0 bytes in 0 blocks
==32139== Rerun with --leak-check=full to see details of leaked memory
==32139== 
==32139== For counts of detected and suppressed errors, rerun with: -v
==32139== Use --track-origins=yes to see where uninitialised values come from
==32139== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault

**Comment by woodpeck** [comment]
If it is not too much to ask, could you use strace to find out which .meta file was opened last before the crash and make that meta file available to me?

**Comment by yvecai** [comment]
I'll do that, but maybe not today.

**Comment by yvecai** [comment]
Easy enough, its /0/0/0/0/0.meta
You can temporarily find it here: http://www6.opensnowmap.org/download/0.meta
Even without this tile, the segfault persist on the first processed.

**Comment by yvecai** [comment]
My bad, I did not mean to close.

**Comment by woodpeck** [comment]
It appears an unitialised variable was erroneously used in determining the file offset. Strange that it ever worked.
