### ISSUE TITLE
How to change meta2tile source, so it makes tiles 512 in size instead of 256?

### ISSUE THREAD

**Issue by bongobongo** [geofabrik/meta2tile#5]
I could not find an option to make meta2tile create tiles with tilesize 512 instead of 256.
Could someone please tell me what to change in source to make it work like this?

**Comment by superrache** [comment]
Tilesize is not set in meta2tile but /etc/renderd.conf

In this file, you can add your layer (default here) with the TILESIZE parameter and also SCALE:

```
[default]
URI=/osm_tiles/
TILEDIR=/var/lib/mod_tile
XML=/path/to/mapnik.xml
HOST=localhost
TILESIZE=512
MINZOOM=0
MAXZOOM=18
TYPE=png image/png
;ASPECTX=1
;ASPECTY=1
SCALE=2.0
```

**Comment by woodpeck** [comment]
Yeah, for meta2tile the individual PNGs inside the metatile files are just blobs of data. meta2tile doesn't have to know how big they are.
